DROP DATABASE IF EXISTS sakila;
DROP DATABASE IF EXISTS myd_test;
DROP DATABASE IF EXISTS myd_test_no_fk;
DROP DATABASE IF EXISTS empty_db;
DROP DATABASE IF EXISTS specific_1;
DROP DATABASE IF EXISTS specific_3;
